version: "3"

services:
  modsen.library-api:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=modsen-meetup-dev
      - POSTGRES_USER=modsen-meetup-dev
      - POSTGRES_PASSWORD=modsen-meetup-dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data/db

volumes:
  postgres-data: